--@Autor: Gutiérrez Castillo Oscar y López Vite Erick Misael
--@Fecha creación: 29/05/2020
--@Descripción: DDL para el sitio EA

-- 
-- TABLE: TIPO_ALMACENAMIENTO_R_ELV_S2 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R_ELV_S2(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_ALMACENAMIENTO_PK PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R_ELV_S2 
--

CREATE TABLE TIPO_MONITOR_R_ELV_S2(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_MONITOR_PK PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R_ELV_S2 
--

CREATE TABLE TIPO_PROCESADOR_R_ELV_S2(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_PROCESADOR_PK PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R_ELV_S2 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R_ELV_S2(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_TARJETA_VIDEO_PK PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;


-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT STATUS_LAPTOP_PK PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: HISTORICO_F1_ELV_S2 
--

CREATE TABLE HISTORICO_F1_ELV_S2(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                  TIMESTAMP(6)     NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_1_PK PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID), 
    CONSTRAINT STA_LAP_HIST_1_STA_LAP_ID_FK FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: LAPTOP_F5_ELV_S2 
--

CREATE TABLE LAPTOP_F5_ELV_S2(
    LAPTOP_ID                 NUMBER(10, 0)     NOT NULL,
    NUM_SERIE                 VARCHAR2(18)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6, 0)      NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)      NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)      NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    CONSTRAINT LAPTOP_5_PK PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT TIP_ALM_LAP_5_TIP_ALM_ID_FK FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO(TIPO_ALMACENAMIENTO_ID),
    CONSTRAINT TIP_MON_LAP_5_TIP_MON_ID_FK FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR(TIPO_MONITOR_ID),
    CONSTRAINT TIP_PRO_LAP_5_TIP_PRO_ID_FK FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR(TIPO_PROCESADOR_ID),
    CONSTRAINT TIP_TAR_LAP_5_TIP_TAR_ID_FK FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO(TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F4_ELV_S2 
--

CREATE TABLE SERVICIO_LAPTOP_F4_ELV_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    FACTURA         BLOB              NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_LAPTOP_4_PK PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID), 
    CONSTRAINT LAP_5_SER_LAP_4_LAP_ID_FK FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_F5_ELV_S2(LAPTOP_ID)
)
;




-- 
-- TABLE: SUCURSAL_F2_ELV_S2 
--

CREATE TABLE SUCURSAL_F2_ELV_S2(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    ES_TALLER      NUMBER(1, 0)     NOT NULL,
    ES_VENTA       NUMBER(1, 0)     NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    LATITUD        BINARY_FLOAT     NOT NULL,
    LONGITUD       BINARY_FLOAT     NOT NULL,
    URL            VARCHAR2(200)    NOT NULL,
    CONSTRAINT SUCURSAL_2_PK PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F2_ELV_S2 
--

CREATE TABLE SUCURSAL_TALLER_F2_ELV_S2(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    DIA_DESCANSO         NUMBER(1, 0)     NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT SUCURSAL_TALLER_2_PK PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT SUC_2_SUC_TAL_2_SUC_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_ELV_S2(SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F2_ELV_S2 
--

CREATE TABLE SUCURSAL_VENTA_F2_ELV_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT SUCURSAL_VENTA_2_PK PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT SUC_2_SUC_VEN_2_SUC_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_ELV_S2(SUCURSAL_ID)
)
;
